require:
  - 'rubocop-erb'

AllCops:
    SuggestExtensions: false
    NewCops: disable
    Exclude:
      - 'db/schema.rb'
      - 'bin/*'
      - 'config/puma.rb'
      - 'config/routes.rb'
      - 'config/environments/production.rb'
      - 'Guardfile'
      - 'app/mailers/application_mailer.rb'

# Disabled rules
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false

# Disabled Layout rules for .erb files
Layout/SpaceBeforeFirstArg:
  Enabled: true
  Exclude:
    - 'app/views/**/*.erb'
Layout/ExtraSpacing:
  Enabled: true
  Exclude:
    - 'app/views/**/*.erb'

# Modified rules  
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
