require:
  - 'rubocop-erb'

AllCops:
    SuggestExtensions: false
    NewCops: disable
    Exclude:
      - 'db/schema.rb'
      - 'bin/*'
      - 'config/puma.rb'
      - 'config/routes.rb'
      - 'config/environments/production.rb'
      - '**/*.html.erb'
      - '**/*.turbo_stream.erb'
      - 'Guardfile'


# Disabled rules
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

# Modified rules  
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']