AllCops:
    SuggestExtensions: false
    NewCops: disable

# Disabled rules
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/Documentation:
  Enabled: false

